services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - echo `docker --version`

install:
  - docker build -t test .

script:
  - docker run test cat /from-built/file.txt
